version: '3.4'

services:
  front:
    image: logs-front
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Front/Dockerfile
   
  back:
    image: logs-back
    build:
      context: .
      dockerfile: Back/Dockerfile

  middle:
    image: logs-middle
    build:
      context: .
      dockerfile: Middle/Dockerfile

  jaeger:    
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"